[project]
name = "DiscordPYComponents"
version = "1.3.0"
description = "Discord Components V2 for discord.py"
authors = [{name="2gm49"}]
dependencies = ["aiohttp"]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

[project.urls]
Homepage = "https://pypi.org/project/DiscordPYComponents/"
Documentation = "https://docs.discord.com/developers/components/overview"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
